export const CART_ADD = "CART_ADD";
export const CART_REMOVE = "CART_REMOVE";
export const CART_RESET = "CART_RESET";
export const CART_ADD_ALLL = "CART_ADD_ALLL";

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAILURE = "PRODUCT_GET_FAILURE";
export const PRODUCT_RESET = "PRODUCT_RESET";

export const PRODUCT_DETAIL_GET_REQUEST = "PRODUCT_DETAIL_GET_REQUEST";
export const PRODUCT_DETAIL_GET_SUCCESS = "PRODUCT_DETAIL_GET_SUCCESS";
export const PRODUCT_DETAIL_GET_FAILURE = "PRODUCT_DETAIL_GET_FAILURE";


export const GOOGLE_LOGIN_SUCCESS="GOOGLE_LOGIN_SUCCESS"
export const GOOGLE_LOGIN_FAILURE="GOOGLE_LOGIN_FAILURE"
export const GOOGLE_LOGIN_REQUEST="GOOGLE_LOGIN_REQUEST";
